[package]
name = "TexasHoldem"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
holdemgame = "0x736ddbfe79a688617f26c712f987d7e2127f6b5f537687d8ecef91be36aa557b"

[dev-addresses]
holdemgame = "0xCAFE"

[dependencies]
CedraFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-framework", rev = "main" }

[dev-dependencies]
