[package]
name = "referral_basic"
version = "0.0.1"

[addresses]
referral_basic = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
