[package]
name = "RandomnessExample"
version = "1.0.0"
authors = []

[addresses]
RandomnessExample = "_"

[dev-addresses]
RandomnessExample = "0xcafe"

[dependencies]
CedraFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-framework", rev = "main" }

[dev-dependencies]
