[package]
name = "dutch_auction"
version = "1.0.0"
authors = []

[addresses]
module_addr = "_"

[dev-addresses]
module_addr = "0x1337"

[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-framework.git"
rev = "mainnet"
subdir = "cedra-framework"

[dependencies.CedraTokenObjects]
git = "https://github.com/cedra-labs/cedra-framework.git"
rev = "mainnet"
subdir = "cedra-token-objects"

[dev-dependencies]
