[package]
name = "expand_nft"
version = "2.0.0"
authors = []

[addresses]
ExpandNFT = "_"

[dev-addresses]
ExpandNFT = "_" 

[dependencies]
CedraFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-framework", rev = "main" }
CedraTokenObjects = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-token-objects", rev = "main" }

[dev-dependencies] 